//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“Scrap.cs”的分部类“public partial class Scrap”}添加属性
// </auto-generated>
//
//  <copyright file="Scrap.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace longquan.gongan.OutStor.Entities
{
    /// <summary>
    /// 实体类：资产报废信息
    /// </summary>
    [Description("资产报废信息")]
    [TableNamePrefix("OutStor")]
    public partial class Scrap : EntityBase<int>, ICreationAudited<int>, IUpdateAudited<int>
    {
        /// <summary>
        /// 获取或设置 资产编号
        /// </summary>
        [DisplayName("资产编号"), Required]
        public string MatNo { get; set; }

        /// <summary>
        /// 获取或设置 报废日期
        /// </summary>
        [DisplayName("报废日期")]
        public DateTime ScrapDate { get; set; }

        /// <summary>
        /// 获取或设置 报废编号
        /// </summary>
        [DisplayName("报废编号")]
        public string ScrapNo { get; set; }

        /// <summary>
        /// 获取或设置 申请部门
        /// </summary>
        [DisplayName("申请部门")]
        public string Dept { get; set; }

        /// <summary>
        /// 获取或设置 审核状态
        /// </summary>
        [DisplayName("审核状态")]
        public string VerifyState { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 资产名称
        /// </summary>
        [DisplayName("资产名称")]
        public string MatName { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

    }
}

