// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 StorWarn 添加方法，可新建文件“AllReportServiceBase.StorWarn.cs”的分部类“public abstract partial class AllReportServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 StorWarn 的业务实现，可新建文件“AllReportService.StorWarn.cs”的分部类“public partial class AllReportService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="AllReportServiceBase.StorWarn.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using longquan.gongan.AllReport.Dtos;
using longquan.gongan.AllReport.Entities;


namespace longquan.gongan.AllReport
{
    public abstract partial class AllReportServiceBase
    {
        /// <summary>
        /// 获取 库存量告警信息查询数据集
        /// </summary>
        public IQueryable<StorWarn> StorWarns
        {
            get { return StorWarnRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查库存量告警信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的库存量告警信息编号</param>
        /// <returns>库存量告警信息是否存在</returns>
        public virtual Task<bool> CheckStorWarnExists(Expression<Func<StorWarn, bool>> predicate, int id = default(int))
        {
            return StorWarnRepository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 添加库存量告警信息
        /// </summary>
        /// <param name="dtos">要添加的库存量告警信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> CreateStorWarns(params StorWarnInputDto[] dtos)
        {
            Check.Validate<StorWarnInputDto, int>(dtos, nameof(dtos));
            return StorWarnRepository.InsertAsync(dtos);
        }
        
        /// <summary>
        /// 更新库存量告警信息
        /// </summary>
        /// <param name="dtos">包含更新信息的库存量告警信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdateStorWarns(params StorWarnInputDto[] dtos)
        {
            Check.Validate<StorWarnInputDto, int>(dtos, nameof(dtos));
            return StorWarnRepository.UpdateAsync(dtos);
        }
    }
}
