// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1. 横向扩展：如需给当前模块添加方法接口，可新建文件“IInStorContract.cs”的分部接口“public partial interface IInStorContract”添加方法，并添加相应新的分部基类 abstract partial class InStorServiceBase 实现新方法
// </auto-generated>
//
//  <copyright file="IInStorContract.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Extensions;

using longquan.gongan.InStor.Dtos;
using longquan.gongan.InStor.Entities;


namespace longquan.gongan.InStor
{
    /// <summary>
    /// 业务契约接口：模块
    /// </summary>
    public partial interface IInStorContract
    {
        #region 资产入库信息业务

        /// <summary>
        /// 获取 资产入库信息查询数据集
        /// </summary>
        IQueryable<InStorMat> InStorMats { get; }

        /// <summary>
        /// 检查资产入库信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的资产入库信息编号</param>
        /// <returns>资产入库信息是否存在</returns>
        Task<bool> CheckInStorMatExists(Expression<Func<InStorMat, bool>> predicate, int id = default(int));
        
        /// <summary>
        /// 添加资产入库信息信息
        /// </summary>
        /// <param name="dtos">要添加的资产入库信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateInStorMats(params InStorMatInputDto[] dtos);
            
        /// <summary>
        /// 更新资产入库信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的资产入库信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateInStorMats(params InStorMatInputDto[] dtos);
            
        /// <summary>
        /// 删除资产入库信息信息
        /// </summary>
        /// <param name="ids">要删除的资产入库信息编号</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> DeleteInStorMats(params int[] ids);
        

        #endregion
        
    }
}
