// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 StoreSum 添加方法，可新建文件“ReportServiceBase.StoreSum.cs”的分部类“public abstract partial class ReportServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 StoreSum 的业务实现，可新建文件“ReportService.StoreSum.cs”的分部类“public partial class ReportService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="ReportServiceBase.StoreSum.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using longquan.gongan.Report.Dtos;
using longquan.gongan.Report.Entities;


namespace longquan.gongan.Report
{
    public abstract partial class ReportServiceBase
    {
        /// <summary>
        /// 获取 库存盘点信息查询数据集
        /// </summary>
        public IQueryable<StoreSum> StoreSums
        {
            get { return StoreSumRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查库存盘点信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的库存盘点信息编号</param>
        /// <returns>库存盘点信息是否存在</returns>
        public virtual Task<bool> CheckStoreSumExists(Expression<Func<StoreSum, bool>> predicate, int id = default(int))
        {
            return StoreSumRepository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 添加库存盘点信息
        /// </summary>
        /// <param name="dtos">要添加的库存盘点信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> CreateStoreSums(params StoreSumInputDto[] dtos)
        {
            Check.Validate<StoreSumInputDto, int>(dtos, nameof(dtos));
            return StoreSumRepository.InsertAsync(dtos);
        }
        
        /// <summary>
        /// 更新库存盘点信息
        /// </summary>
        /// <param name="dtos">包含更新信息的库存盘点信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdateStoreSums(params StoreSumInputDto[] dtos)
        {
            Check.Validate<StoreSumInputDto, int>(dtos, nameof(dtos));
            return StoreSumRepository.UpdateAsync(dtos);
        }
        
        /// <summary>
        /// 删除库存盘点信息
        /// </summary>
        /// <param name="ids">要删除的库存盘点信息编号</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> DeleteStoreSums(params int[] ids)
        {
            Check.NotNull(ids, nameof(ids));
            return StoreSumRepository.DeleteAsync(ids);
        }
    }
}
