// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前控制器添加API，请在控制器类型 StorWarnController.cs 进行添加
//      2.纵向扩展：如需要重写当前控制器的API实现，请在控制器类型 StorWarnController.cs 进行继承重写
// </auto-generated>
//
//  <copyright file="StorWarnBase.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using OSharp.AspNetCore.Mvc;
using OSharp.AspNetCore.Mvc.Filters;
using OSharp.AspNetCore.UI;
using OSharp.Caching;
using OSharp.Authorization.Functions;
using OSharp.Authorization.Modules;
using OSharp.Data;
using OSharp.Entity;
using OSharp.Filter;
using OSharp.Security;

using longquan.gongan.AllReport;
using longquan.gongan.AllReport.Dtos;
using longquan.gongan.AllReport.Entities;


namespace longquan.gongan.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// 管理控制器基类: 库存量告警信息
    /// </summary>
    [ModuleInfo(Position = "AllReport", PositionName = "其他模块")]
    [Description("管理-库存量告警信息")]
    public abstract class StorWarnControllerBase : AdminApiController
    {
        /// <summary>
        /// 初始化一个<see cref="StorWarnController"/>类型的新实例
        /// </summary>
        protected StorWarnControllerBase(IAllReportContract allReportContract,
            IFilterService filterService)
        {
            AllReportContract = allReportContract;
            FilterService = filterService;
        }

        /// <summary>
        /// 获取或设置 数据过滤服务对象
        /// </summary>
        protected IFilterService FilterService { get; }

        /// <summary>
        /// 获取或设置 模块业务契约对象
        /// </summary>
        protected IAllReportContract AllReportContract { get; }
        
        /// <summary>
        /// 读取库存量告警列表信息
        /// </summary>
        /// <param name="request">页请求信息</param>
        /// <returns>库存量告警列表分页信息</returns>
        [HttpPost]
        [ModuleInfo]
        [Description("读取")]
        public virtual PageData<StorWarnOutputDto> Read(PageRequest request)
        {
            Check.NotNull(request, nameof(request));

            Expression<Func<StorWarn, bool>> predicate = FilterService.GetExpression<StorWarn>(request.FilterGroup);
            var page = AllReportContract.StorWarns.ToPage<StorWarn, StorWarnOutputDto>(predicate, request.PageCondition);

            return page.ToPageData();
        }
        
        /// <summary>
        /// 新增库存量告警信息
        /// </summary>
        /// <param name="dtos">库存量告警信息输入DTO</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("新增")]
        public virtual async Task<AjaxResult> Create(StorWarnInputDto[] dtos)
        {
            Check.NotNull(dtos, nameof(dtos));
            OperationResult result = await AllReportContract.CreateStorWarns(dtos);
            return result.ToAjaxResult();
        }
        
        /// <summary>
        /// 更新库存量告警信息
        /// </summary>
        /// <param name="dtos">库存量告警信息输入DTO</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("更新")]
        public virtual async Task<AjaxResult> Update(StorWarnInputDto[] dtos)
        {
            Check.NotNull(dtos, nameof(dtos));
            OperationResult result = await AllReportContract.UpdateStorWarns(dtos);
            return result.ToAjaxResult();
        }
    }
}
