// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前控制器添加API，请在控制器类型 DateWarnController.cs 进行添加
//      2.纵向扩展：如需要重写当前控制器的API实现，请在控制器类型 DateWarnController.cs 进行继承重写
// </auto-generated>
//
//  <copyright file="DateWarnBase.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using OSharp.AspNetCore.Mvc;
using OSharp.AspNetCore.Mvc.Filters;
using OSharp.AspNetCore.UI;
using OSharp.Caching;
using OSharp.Authorization.Functions;
using OSharp.Authorization.Modules;
using OSharp.Data;
using OSharp.Entity;
using OSharp.Filter;
using OSharp.Security;

using longquan.gongan.Report;
using longquan.gongan.Report.Dtos;
using longquan.gongan.Report.Entities;


namespace longquan.gongan.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// 管理控制器基类: 质保期告警信息
    /// </summary>
    [ModuleInfo(Position = "Report", PositionName = "456模块")]
    [Description("管理-质保期告警信息")]
    public abstract class DateWarnControllerBase : AdminApiController
    {
        /// <summary>
        /// 初始化一个<see cref="DateWarnController"/>类型的新实例
        /// </summary>
        protected DateWarnControllerBase(IReportContract reportContract,
            IFilterService filterService)
        {
            ReportContract = reportContract;
            FilterService = filterService;
        }

        /// <summary>
        /// 获取或设置 数据过滤服务对象
        /// </summary>
        protected IFilterService FilterService { get; }

        /// <summary>
        /// 获取或设置 模块业务契约对象
        /// </summary>
        protected IReportContract ReportContract { get; }
        
        /// <summary>
        /// 读取质保期告警列表信息
        /// </summary>
        /// <param name="request">页请求信息</param>
        /// <returns>质保期告警列表分页信息</returns>
        [HttpPost]
        [ModuleInfo]
        [Description("读取")]
        public virtual PageData<DateWarnOutputDto> Read(PageRequest request)
        {
            Check.NotNull(request, nameof(request));

            Expression<Func<DateWarn, bool>> predicate = FilterService.GetExpression<DateWarn>(request.FilterGroup);
            var page = ReportContract.DateWarns.ToPage<DateWarn, DateWarnOutputDto>(predicate, request.PageCondition);

            return page.ToPageData();
        }
        
        /// <summary>
        /// 新增质保期告警信息
        /// </summary>
        /// <param name="dtos">质保期告警信息输入DTO</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("新增")]
        public virtual async Task<AjaxResult> Create(DateWarnInputDto[] dtos)
        {
            Check.NotNull(dtos, nameof(dtos));
            OperationResult result = await ReportContract.CreateDateWarns(dtos);
            return result.ToAjaxResult();
        }
        
        /// <summary>
        /// 更新质保期告警信息
        /// </summary>
        /// <param name="dtos">质保期告警信息输入DTO</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("更新")]
        public virtual async Task<AjaxResult> Update(DateWarnInputDto[] dtos)
        {
            Check.NotNull(dtos, nameof(dtos));
            OperationResult result = await ReportContract.UpdateDateWarns(dtos);
            return result.ToAjaxResult();
        }
        
        /// <summary>
        /// 删除质保期告警信息
        /// </summary>
        /// <param name="ids">质保期告警信息编号</param>
        /// <returns>JSON操作结果</returns>
        [HttpPost]
        [ModuleInfo]
        [DependOnFunction("Read")]
        [ServiceFilter(typeof(UnitOfWorkAttribute))]
        [Description("删除")]
        public virtual async Task<AjaxResult> Delete(int[] ids)
        {
            Check.NotNull(ids, nameof(ids));
            OperationResult result = await ReportContract.DeleteDateWarns(ids);
            return result.ToAjaxResult();
        }
    }
}
