// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“AssetCollectionOutputDto.cs”的分部类“public partial class AssetCollectionOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="AssetCollectionOutputDto.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using longquan.gongan.OutStor.Entities;

namespace longquan.gongan.OutStor.Dtos
{
    /// <summary>
    /// 输入DTO：资产领用信息
    /// </summary>
    [MapFrom(typeof(AssetCollection))]
    [Description("资产领用信息")]
    public partial class AssetCollectionOutputDto : IOutputDto, IDataAuthEnabled
    {
        /// <summary>
        /// 初始化一个<see cref="AssetCollectionOutputDto"/>类型的新实例
        /// </summary>
        public AssetCollectionOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="AssetCollectionOutputDto"/>类型的新实例
        /// </summary>
        public AssetCollectionOutputDto(AssetCollection entity)
        {
            Id = entity.Id;
            ColVoucher = entity.ColVoucher;
            ColDeptno = entity.ColDeptno;
            ColStaffno = entity.ColStaffno;
            ColMatno = entity.ColMatno;
            ColDate = entity.ColDate;
            ColNumber = entity.ColNumber;
            Remark = entity.Remark;
            Other = entity.Other;
            CreatorId = entity.CreatorId;
            CreatedTime = entity.CreatedTime;
            LastUpdaterId = entity.LastUpdaterId;
            LastUpdatedTime = entity.LastUpdatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

        /// <summary>
        /// 获取或设置 领用凭证
        /// </summary>
        [DisplayName("领用凭证")]
        public string ColVoucher { get; set; }

        /// <summary>
        /// 获取或设置 领用部门编码
        /// </summary>
        [DisplayName("领用部门编码")]
        public string ColDeptno { get; set; }

        /// <summary>
        /// 获取或设置 领用人员编码
        /// </summary>
        [DisplayName("领用人员编码")]
        public string ColStaffno { get; set; }

        /// <summary>
        /// 获取或设置 领用物品编码
        /// </summary>
        [DisplayName("领用物品编码")]
        public string ColMatno { get; set; }

        /// <summary>
        /// 获取或设置 领用日期
        /// </summary>
        [DisplayName("领用日期")]
        public DateTime ColDate { get; set; }

        /// <summary>
        /// 获取或设置 领用数量
        /// </summary>
        [DisplayName("领用数量")]
        public double ColNumber { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 其他
        /// </summary>
        [DisplayName("其他")]
        public string Other { get; set; }

        /// <summary>
        /// 获取或设置 创建者
        /// </summary>
        [DisplayName("创建者")]
        public int? CreatorId { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

        /// <summary>
        /// 获取或设置 是否可更新的数据权限状态
        /// </summary>
        public bool Updatable { get; set; }

        /// <summary>
        /// 获取或设置 是否可删除的数据权限状态
        /// </summary>
        public bool Deletable { get; set; }

    }
}
