// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“AssetCollectionInputDto.cs”的分部类“public partial class AssetCollectionInputDto”}添加属性
// </auto-generated>
//
//  <copyright file="AssetCollectionInputDto.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using longquan.gongan.OutStor.Entities;


namespace longquan.gongan.OutStor.Dtos
{
    /// <summary>
    /// 输入DTO：资产领用信息
    /// </summary>
    [MapTo(typeof(AssetCollection))]
    [Description("资产领用信息")]
    public partial class AssetCollectionInputDto : IInputDto<int>
    {
        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

        /// <summary>
        /// 获取或设置 领用凭证
        /// </summary>
        [DisplayName("领用凭证"), Required]
        public string ColVoucher { get; set; }

        /// <summary>
        /// 获取或设置 领用部门编码
        /// </summary>
        [DisplayName("领用部门编码")]
        public string ColDeptno { get; set; }

        /// <summary>
        /// 获取或设置 领用人员编码
        /// </summary>
        [DisplayName("领用人员编码")]
        public string ColStaffno { get; set; }

        /// <summary>
        /// 获取或设置 领用物品编码
        /// </summary>
        [DisplayName("领用物品编码")]
        public string ColMatno { get; set; }

        /// <summary>
        /// 获取或设置 领用日期
        /// </summary>
        [DisplayName("领用日期")]
        public DateTime ColDate { get; set; }

        /// <summary>
        /// 获取或设置 领用数量
        /// </summary>
        [DisplayName("领用数量")]
        public double ColNumber { get; set; }

        /// <summary>
        /// 获取或设置 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remark { get; set; }

        /// <summary>
        /// 获取或设置 其他
        /// </summary>
        [DisplayName("其他")]
        public string Other { get; set; }

        /// <summary>
        /// 获取或设置 审核状态
        /// </summary>
        [DisplayName("审核状态")]
        public string VerifyState { get; set; }

    }
}
