// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，请在控制器类型 BaseDataService 进行继承重写
// </auto-generated>
//
//  <copyright file="IBaseDataServiceBase.generated.cs" company="longquan.gongan">
//      longquan.gongan
//  </copyright>
//  <site>http://longquan.gongan</site>
//  <last-editor>longquan.gongan</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Threading.Tasks;

using OSharp.Core.Systems;
using OSharp.Data;
using OSharp.Entity;
using OSharp.EventBuses;
using OSharp.Extensions;
using OSharp.Identity;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using longquan.gongan.BaseData.Dtos;
using longquan.gongan.BaseData.Entities;


namespace longquan.gongan.BaseData
{
    /// <summary>
    /// 业务实现基类：模块
    /// </summary>
    public abstract partial class BaseDataServiceBase : IBaseDataContract
    {
        /// <summary>
        /// 初始化一个<see cref="BaseDataService"/>类型的新实例
        /// </summary>
        protected BaseDataServiceBase(IServiceProvider provider)
        {
            ServiceProvider = provider;
            Logger = provider.GetLogger(GetType());
        }
    
        #region 属性

        /// <summary>
        /// 获取或设置 服务提供者对象
        /// </summary>
        protected IServiceProvider ServiceProvider { get; }

        /// <summary>
        /// 获取或设置 日志对象
        /// </summary>
        protected ILogger Logger { get; }

        /// <summary>
        /// 获取或设置 供应商数据信息仓储对象
        /// </summary>
        protected IRepository<BaseSup, int> BaseSupRepository => ServiceProvider.GetService<IRepository<BaseSup, int>>();
        
        /// <summary>
        /// 获取或设置 分类数据信息仓储对象
        /// </summary>
        protected IRepository<BaseKind, int> BaseKindRepository => ServiceProvider.GetService<IRepository<BaseKind, int>>();
        
        /// <summary>
        /// 获取或设置 物品数据信息仓储对象
        /// </summary>
        protected IRepository<BaseMat, int> BaseMatRepository => ServiceProvider.GetService<IRepository<BaseMat, int>>();

        /// <summary>
        /// 获取或设置 部门数据信息仓储对象
        /// </summary>
        protected IRepository<BaseDept, int> BaseDeptRepository => ServiceProvider.GetService<IRepository<BaseDept, int>>();

        /// <summary>
        /// 获取或设置 人员数据信息仓储对象
        /// </summary>
        protected IRepository<BaseStaff, int> BaseStaffRepository => ServiceProvider.GetService<IRepository<BaseStaff, int>>();

        /// <summary>
        /// 获取或设置 仓库数据信息仓储对象
        /// </summary>
        protected IRepository<BaseStore, int> BaseStoreRepository => ServiceProvider.GetService<IRepository<BaseStore, int>>();

        /// <summary>
        /// 获取 事件总线
        /// </summary>
        protected IEventBus EventBus => ServiceProvider.GetService<IEventBus>();

        /// <summary>
        /// 获取 设置存储对象
        /// </summary>
        protected IKeyValueStore KeyValueStore => ServiceProvider.GetService<IKeyValueStore>();

        #endregion
    }
}
